### PR TITLE
profile/dropdown: arrow to indicate select as dropdown

### LINKED ISSUE #2290: account settings: Select list look like input fields
**URL:** 
https://opin-dev.liqd.net/en/accounts/profile/

**user:** 
logged-in participant

**expected behaviour:** 
Select lists should have an arrow or UI element to indicate that they can be clicked to make a select list appear and to differentiate them from input fields.

**behaviour:** 
The select lists look like text input fields.

**important screensize:**
all sizes

**device & browser:** 
macOS 11.4, Safari 11.4.1

**Comment/Question:** 

Screenshot?
Bildschirmfoto 2021-08-02 um 17 47 28

### PR DESCRIPTION
**Pull request by khamui**
closes #2290

### CODE REVIEW

**Review by fuzzylogic2000 — COMMENTED** [review]
Yeah! That brings the arrows back! I think everything in opin should have not rounded corners, though. (But change that only if it's easy. :))

**Comment by phillimorland** [comment]
@fuzzylogic2000 `border-radius: 0` is right for no rounded corners, or did you find some elsewhere?

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 `border-radius: 0` is right for no rounded corners, or did you find some elsewhere?

@phillimorland For me the selects in the user settings were round in this PR.

**Comment by khamui** [comment]
oh strange @fuzzylogic2000 , i checked again and for me its without border radius. 🤨

Bildschirmfoto 2021-09-02 um 15 44 38

**Comment by phillimorland** [comment]
@fuzzylogic2000 @khamui selects are tricky, we do partially overwrite them but they can still have sometimes browser specific styling sneaks in, I didn't get any rounded corners when I checked it so I would go with merging

**Pull request merged**
