### PR TITLE
Ks 2020 10 birht date issue fixing

### LINKED ISSUE #1946: After adding my birth date to my account, I can't access my account settings anymore
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** It saves the date (as you can see in the profile), but doesn't have a way to display it in the account settings
**important screensize:**
**device & browser:** 
**Comment/Question:** Sentry: https://sentry.liqd.net/sentry/opin-prod/issues/864/
`Environment:

Request Method: GET
Request URL: http://localhost:8001/de/accounts/profile/

Django Version: 2.2.14
Python Version: 3.7.5
Installed Applications:
['home',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.contrib.styleguide',
 'wagtail.contrib.settings',
 'modelcluster',
 'taggit',
 'widget_tweaks',
 'easy_thumbnails',
 'parler',
 'ckeditor',
 'ckeditor_uploader',
 'background_task',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django_countries',
 'rest_framework',
 'rules.apps.AutodiscoverRulesConfig',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'micawber.contrib.mcdjango',
 'adhocracy4.administrative_districts',
 'adhocracy4.images',
 'adhocracy4.forms',
 'adhocracy4.phases',
 'adhocracy4.projects',
 'adhocracy4.ratings',
 'adhocracy4.reports',
 'adhocracy4.modules',
 'adhocracy4.categories',
 'adhocracy4.comments',
 'adhocracy4.comments_async',
 'adhocracy4.maps',
 'adhocracy4.filters',
 'adhocracy4.rules',
 'adhocracy4.ckeditor',
 'adhocracy4.dashboard',
 'adhocracy4.polls',
 'adhocracy4.organisations',
 'euth.users',
 'euth.actions',
 'euth.organisations',
 'euth.projects',
 'euth.ideas',
 'euth.dashboard',
 'euth.accounts',
 'euth.memberships',
 'euth.documents',
 'euth.exports',
 'euth.offlinephases',
 'euth.maps',
 'euth.follows',
 'euth.blueprints',
 'euth.contrib',
 'euth.communitydebate',
 'debug_toolbar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django_cloudflare_push.middleware.push_middleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'euth.contrib.middleware.TimezoneMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'wagtail.core.middleware.SiteMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']

Template error:
In template /home/katharina/a4-opin/euth_wagtail/templates/base.html, error at line 0
   'DateInput' object has no attribute '_format_value'
   1 : {% load base_tags i18n static url_translations wagtailuserbar %}
   2 : {% get_current_language as LANGUAGE_CODE %}
   3 : 
   4 : 
   5 : <!DOCTYPE html>
   6 : 
   7 : 
   8 : 
   9 :  <html class="no-js" lang="{{ request.LANGUAGE_CODE }}"> 
   10 :     <head>

Traceback:

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  145.                 response = self.process_exception_by_middleware(e, request)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  143.                 response = response.render()

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/response.py" in render
  106.             self.content = self.rendered_content

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/response.py" in rendered_content
  83.         content = template.render(context, self._request)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render
  171.                     return self._render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  150.             return compiled_parent._render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  150.             return compiled_parent._render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  62.                 result = block.nodelist.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  62.                 result = block.nodelist.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/defaulttags.py" in render
  209.                     nodelist.append(node.render_annotated(context))

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/defaulttags.py" in render
  209.                     nodelist.append(node.render_annotated(context))

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/defaulttags.py" in render
  309.                 return nodelist.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/defaulttags.py" in render
  309.                 return nodelist.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/widget_tweaks/templatetags/widget_tweaks.py" in render
  229.         return str(bounded_field)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/utils/html.py" in <lambda>
  388.     klass.__str__ = lambda self: mark_safe(klass_str(self))

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/forms/boundfield.py" in __str__
  33.         return self.as_widget()

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/widget_tweaks/templatetags/widget_tweaks.py" in as_widget
  36.         html = old_as_widget(widget, attrs, only_initial)

File "/home/katharina/a4-opin/venv/lib/python3.7/site-packages/django/forms/boundfield.py" in as_widget
  93.             renderer=self.form.renderer,

File "/home/katharina/a4-opin/euth/contrib/widgets.py" in render
  40.                     'data-default-date': self._format_value(value)

Exception Type: AttributeError at /de/accounts/profile/
Exception Value: 'DateInput' object has no attribute '_format_value'`

### PR DESCRIPTION
**Pull request by Rineee**
the _format_value() method was removed [here](/liqd/a4-opin/commit/52fd55b134185d34b92a36a674dacb25e4e30257#diff-197c914dc8856ba13ee89bc213edbc2f) and as I understood it, we dont need the default date anymore bc of flatpickr? At least it works all fine without..

fixes  #1946

### CODE REVIEW

**Review by fuzzylogic2000 — APPROVED** [review]
Kihihihi!

**Comment by fuzzylogic2000** [comment]
Ohhh nooo, the test coverage falls. And here it's really unfortunate because it falls below 90% :cry: I am so sorry! I will äh merge and we add tests tomorrow?

**Comment by Rineee** [comment]
I can also quickly add a test! We cant loose our 90%, no way! :)

**Review by fuzzylogic2000 — APPROVED** [review]
Wow! Nice! +0.6!!

**Pull request merged**
