### PR TITLE
Pm 2021 07 finish a4 update

### PR DESCRIPTION
**Pull request by phillimorland**

### CODE REVIEW

**Comment by phillimorland** [comment]
this is reliant on https://github.com/liqd/adhocracy4/pull/791 when that is merged will update hash

**Review by fuzzylogic2000 — APPROVED** [review]
Nice! I could also update the hash - did that locally anyway. But you also want to delete the unused styles?

**Comment by phillimorland** [comment]
@fuzzylogic2000 yes need to do little more tidying, i just saw them when checking the compare.

**Comment by phillimorland** [comment]
@fuzzylogic2000 ok ready :)

**Pull request merged**
