### PR TITLE
ideas/views: return 404 instead of server error if module does not ex…

### PR DESCRIPTION
**Pull request by Rineee**
…ist anymore

hopefully fixes https://sentry.liqd.net/sentry/opin-prod/issues/750/events/37858/

### CODE REVIEW

**Review by fuzzylogic2000 — COMMENTED** [review]
It looks good. But how can we not have the module? It needs to be there and should be wherever we click the button to add an idea. :thinking: Was it not published or something like that?

**Comment by fuzzylogic2000** [comment]
And why is self a whole module query set? Is this a problem from multi modules or something like that? This is all a bit weird.

**Comment by Rineee** [comment]
> It looks good. But how can we not have the module? It needs to be there and should be wherever we click the button to add an idea. thinking Was it not published or something like that?

I think we can only not have the module if it is really not there anymore, so if the project was deleted. Couldn't it be that people send the link around? 
I am also not sure if this is it, but I figured that returning the get_object_or_404() instead of just get() makes sense anyway and maybe its worth a try ..

**Comment by Rineee** [comment]
> And why is self a whole module query set? Is this a problem from multi modules or something like that? This is all a bit weird.

Which self and where?

**Review by fuzzylogic2000 — APPROVED** [review]
Alright! Talking about it this seems like the only option!

**Pull request merged**
