### PR TITLE
Pm 2020 04 async comments

### PR DESCRIPTION
**Pull request by phillimorland**
initial adding comments, not well styled but will wait for designs before sinking time into it

### CODE REVIEW

**Comment by phillimorland** [comment]
@fuzzylogic2000 loading now fixed, the user image I didn't bother with as its a design thing so figured I would wait for that decision?

**Comment by Rineee** [comment]
@phillimorland The editing of comments doesn't work? But deleting is possible.

**Comment by fuzzylogic2000** [comment]
@Rineee As a user? Or admin?

**Comment by Rineee** [comment]
> @Rineee As a user? Or admin?

As an admin.

**Comment by Rineee** [comment]
> > @Rineee As a user? Or admin?
> 
> As an admin.

No actually both admin and user :)

**Pull request merged**
