### PR TITLE
makefile: does it build with --legacy-peer-deps

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
Doesn't work locally, but it builds, so we can merge and add it to the release?

### CODE REVIEW

**Review by goapunk — APPROVED** [review]
looks good to me, installing also worked locally for me (make install)

**Comment by goapunk** [comment]
@fuzzylogic2000 ci fails because of the changed timezone information, do we care? should we add it?

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 ci fails because of the changed timezone information, do we care? should we add it?

@goapunk I tried to last week: after installing locally, makemigrations didn't add migrations, though. So, I didn't know what to do there.

**Comment by goapunk** [comment]
> > @fuzzylogic2000 ci fails because of the changed timezone information, do we care? should we add it?
> 
> @goapunk I tried to last week: after installing locally, makemigrations didn't add migrations, though. So, I didn't know what to do there.

I pushed a migration

**Pull request merged**
