### PR TITLE
locale: translations pulled from transifex

### PR DESCRIPTION
**Pull request by sabinammm**
US #5530, Task #5530
@Rineee When I pulled, there were only strings from German and Slovenian, is this correct? And there is nothing else that needs to be done here?

### CODE REVIEW

**Comment by Rineee** [comment]
> US #5530, Task #5530 @Rineee When I pulled, there were only strings from German and Slovenian, is this correct? And there is nothing else that needs to be done here?

No, I dont think so, the other languages have also new translations, that should be there.. lets look at it tomorrow!

**Comment by hello-kathi** [comment]
@Rineee 
We translated all languages so there should be 10, maybe 9 if English is not counting. ;) sorry for Klugscheissern.

**Review by fuzzylogic2000 — APPROVED** [review]
Looks good (I only looked at the first three languages, though...)

**Comment by Rineee** [comment]
@sabinammm Sorry, this is a bit late and also not super important, but for next time: we normally also do 'make po' after translations are pulled, because the formatting is a bit different then (only one code reference in one line). So this way, we always have the same format committed.. in the instructions it is [here](https://github.com/liqd/a4-opin/blob/68c70df052005ea57dda95ad739763289e64b00e/docs/translations.md?plain=1#L55), not very explicit though. Better in aplus [here](https://github.com/liqd/adhocracy-plus/blob/main/docs/languages_and_translations.md?plain=1#L33-L37). If you have time, maybe you could update that in opin? Then you could also add the force pulling.. thanks!

**Pull request merged**
