### PR TITLE
Pm 2021 04 js updates

### PR DESCRIPTION
**Pull request by phillimorland**
Using the vendor chunk is, IIUC, a leftover from Webpack <= 3 times.
Webpack >= 4 promote a different kind of chunk splitting. This is
a step into that direction.

The probably biggest benefit is that there's now a single big adhocracy4
entry point which includes all base dependencies, avoid odd ordering issues
and making it clearer where to add stuff to.

Port of some improvements found in liqd/adhocracy-plus#1128, which again was a port of #3440

### CODE REVIEW

**Comment by phillimorland** [comment]
@fuzzylogic2000 this is now working ontop of your pull request, I just made this branch as a safety, would you prefer it's cherry picked to your branch?

**Comment by fuzzylogic2000** [comment]
Perfect! Then @Rineee will have to review my PR first and we do a rebase once we have merged. :)

**Review by fuzzylogic2000 — COMMENTED** [review]
For me the comments do not work locally (in the poll module and also in the brainstorming module). 
```
Uncaught TypeError: _adhocracy.comments_async is undefined
    init webpack://[name]/./euth_wagtail/assets/js/app.js?:27
```

**Comment by phillimorland** [comment]
@fuzzylogic2000 oupps, should be fixed now

**Comment by Rineee** [comment]
> Perfect! Then @Rineee will have to review my PR first and we do a rebase once we have merged. :)

I just merged https://github.com/liqd/a4-opin/pull/2146

**Comment by fuzzylogic2000** [comment]
Cool, I will try this out again and rebase!

**Review by fuzzylogic2000 — APPROVED** [review]
Very nice!
But we still have to fix the poll bug.

**Pull request merged**
